pipeline {
    agent any
    tools {
        git 'Git' // Ensure Git is configured in Global Tool Configuration
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    if (fileExists('requirements.txt')) {
                        bat 'pip install -r requirements.txt'
                    } else {
                        echo 'No requirements.txt found. Skipping dependencies.'
                    }
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    def testFiles = [
                        'test_1_login.py',
                        'test_2_product_selection.py',
                        'test_3_cart_info.py',
                        'test_4_checkout_step_one_page.py',
                        'test_5_checkout_step_two_page.py'
                    ]

                    boolean testsFailed = false

                    for (testFile in testFiles) {
                        if (fileExists(testFile)) {
                            try {
                                bat "python ${testFile}"
                            } catch(Exception e) {
                                echo "Test failed: ${testFile}"
                                testsFailed = true
                            }
                        } else {
                            error "Test file missing: ${testFile}"
                        }
                    }

                    if(testsFailed) {
                        currentBuild.result = 'FAILURE'
                        error 'One or more tests failed'
                    }
                }
            }
        }
        stage('Code Quality') {
            steps {
                script {
                    if (fileExists('__init__.py')) {
                        bat 'pip install pylint' // Ensure pylint is installed
                        bat 'pylint *.py'
                    } else {
                        echo 'No Python files found for code analysis'
                    }
                }
            }
        }
    }
}
