def books_collection():
    collection = {'1001': {'Title': 'Ramayana', 'Author': 'Valmiki', 'Genre': 'Mythology', 'Copies': 10},
                  '1002': {'Title': 'Mahabharata', 'Author': 'Ami Ganatra', 'Genre': 'Mythology', 'Copies': 20},
                  '1003': {'Title': 'Bhagavad Gita', 'Author': 'Krishna', 'Genre': 'Mythology', 'Copies': 5},
                  '1004': {'Title': 'Yayati', 'Author': 'Vi. Sa. Khandekar', 'Genre': 'Mythology', 'Copies': 12},
                  '1005': {'Title': '7 Secrets of Vishnu', 'Author': 'Devdatta Patnayak', 'Genre': 'Mythology',
                           'Copies': 5},
                  '1006': {'Title': 'Mrityunjay', 'Author': 'Shivaji Sawant', 'Genre': 'Mythology', 'Copies': 14},
                  '2001': {'Title': 'C Language', 'Author': 'Dennis Ritchie', 'Genre': 'Programming', 'Copies': 30},
                  '2002': {'Title': 'CPP Language', 'Author': 'Bjarne Stroustrup', 'Genre': 'Programming',
                           'Copies': 10},
                  '2003': {'Title': 'Core Java', 'Author': 'James Gosling', 'Genre': 'Programming', 'Copies': 40},
                  '2004': {'Title': 'Simply Python', 'Author': 'Guido Van Rossum', 'Genre': 'Programming',
                           'Copies': 30},
                  '2005': {'Title': 'Data Structure', 'Author': 'Andrew Tanenbaum', 'Genre': 'Programming',
                           'Copies': 30},
                  '3001': {'Title': 'Sapiens', 'Author': 'Yuval Harari', 'Genre': 'World History', 'Copies': 5},
                  '3002': {'Title': 'The Dawn of Everything', 'Author': 'David Graeber', 'Genre': 'World History',
                           'Copies': 15},
                  '3003': {'Title': 'Silk Roads', 'Author': 'Peter Frankopan', 'Genre': 'World History', 'Copies': 6},
                  '3004': {'Title': 'The Cold War', 'Author': 'Odd Arne Westad', 'Genre': 'World History',
                           'Copies': 25},
                  '3005': {'Title': 'India: A Wounded Civilization', 'Author': 'V. S. Naipaul',
                           'Genre': 'World History',
                           'Copies': 8},
                  '4001': {'Title': 'Sophie\'s World', 'Author': 'Jostein Gaarder', 'Genre': 'Philosophy', 'Copies': 7},
                  '4002': {'Title': 'The Republic', 'Author': 'Plato', 'Genre': 'Philosophy', 'Copies': 3},
                  '4003': {'Title': 'Candid', 'Author': 'Voltaire', 'Genre': 'Philosophy', 'Copies': 12},
                  '4004': {'Title': 'Das Kapital', 'Author': 'Karl Marx', 'Genre': 'Philosophy', 'Copies': 2},
                  '4005': {'Title': 'Beyond Good and Evil', 'Author': 'Friedrich Nietzsche ', 'Genre': 'Philosophy',
                           'Copies': 7},
                  '4006': {'Title': 'Metaphysics', 'Author': 'Aristotle ', 'Genre': 'Philosophy', 'Copies': 7},
                  '5001': {'Title': 'Great Expectations', 'Author': 'Charles Dickens', 'Genre': 'Crime', 'Copies': 5},
                  '5002': {'Title': 'The Woman in White', 'Author': 'Wilkie Collins', 'Genre': 'Crime', 'Copies': 6},
                  '5003': {'Title': 'Crisis', 'Author': 'Robin Cook', 'Genre': 'Crime', 'Copies': 2},
                  '5004': {'Title': 'Black Lis', 'Author': 'Brad Thor', 'Genre': 'Crime', 'Copies': 1},
                  '6001': {'Title': 'Double Indemnity', 'Author': 'James Cain', 'Genre': 'Thriller', 'Copies': 4},
                  '6002': {'Title': 'Casino Royale', 'Author': 'Ian Flemmings', 'Genre': 'Thriller', 'Copies': 3},
                  '6003': {'Title': 'The Long Goodbye', 'Author': 'Raymond Chandler', 'Genre': 'Thriller', 'Copies': 6},
                  '7001': {'Title': 'The God we trust', 'Author': 'Jean Shephard', 'Genre': 'Comedy', 'Copies': 16},
                  '7002': {'Title': 'Braywatch', 'Author': 'Ross', 'Genre': 'Comedy', 'Copies': 20},
                  '7003': {'Title': 'So lucky', 'Author': 'Dawn O\'Porter', 'Genre': 'Comedy', 'Copies': 6},
                  '7004': {'Title': 'Test this collection', 'Author': ' S R B', 'Genre': 'Programming', 'Copies': 10}
                  }
    return collection
